In [11]:
import numpy as np
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [26]:
import numpy as np
a=np.ndarray(10)
b=np.ndarray(10)
counter1=1
counter2=10
for i in range(0,len(a)):
    a[i]=counter1
    counter1+=1
    b[i]=counter2
    counter2-=1


#Functions
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.abs(a))
print(np.pi)
print(np.absolute(a))

print(np.arccos(a))
print(np.arccosh(a))
print(np.arcsin(a))
print(np.arcsinh(a))
print(np.arctan())
print(np.arctan2())
print(np.arctanh())

print(np.ceil())
print(np.cbrt())
print(np.conj())
print(np.greater())
print(np.greater_equal())
print(np.disp())
print(np.sin())
print(np.cos())
print(np.tan())
print(np.sqrt())
print(np.spacing())
print(np.reciprocal())
print(np.logical_and())
print(np.logical_or())
print(np.logical_not())
print(np.logical_xor())
print(np.bitwise_xor())
print(np.bitwise_and())
print(np.bitwise_or())
print(np.deg2rad())
print(np.degrees())
print(np.fmax())
print(np.fmin())
print(np.set_numeric_ops())
print(np.set_string_function())
print(np.set_module())
print(np.maximum())
print(np.matmul())
print(np.lcm())
print(np.less())
print(np.less_equal())

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]


TypeError: expected sequence object with len >= 0 or a single integer